import { Router, Request, Response } from 'express';
import pool from '../../db/connection';
import { TicketItem, AddItemsRequest } from '../../types/index';
import { shouldSimulateFailure, simulateDelay } from '../../utils/helpers';

const router = Router();

// GET /api/v1/tickets/:ticketId/items - Get all items for a ticket
router.get('/:ticketId/items', async (req: Request, res: Response) => {
  try {
    await simulateDelay();
    
    if (shouldSimulateFailure()) {
      return res.status(500).json({
        success: false,
        error: 'Simulated server error',
      });
    }

    const { ticketId } = req.params;

    // Verify ticket exists
    const ticketResult = await pool.query(
      'SELECT * FROM tickets WHERE tickets.id = $1',
      [ticketId]
    );

    if (ticketResult.rows.length === 0) {
      return res.status(404).json({
        success: false,
        error: 'Ticket not found',
      });
    }

    const itemsResult = await pool.query(
      `SELECT
        ticket_items.id,
        ticket_items.ticket_id,
        ticket_items.name,
        ticket_items.price,
        ticket_items.quantity,
        ticket_items.paid_amount,
        ticket_items.created_at
      FROM ticket_items
      WHERE ticket_items.ticket_id = $1
      ORDER BY ticket_items.created_at`,
      [ticketId]
    );

    const items: TicketItem[] = itemsResult.rows.map((itemRow: any) => {
      const paidAmount = itemRow.paid_amount || 0;
      const itemTotalPrice = itemRow.price * itemRow.quantity;
      return {
        id: itemRow.id,
        ticket_id: itemRow.ticket_id,
        name: itemRow.name,
        price: itemRow.price,
        quantity: itemRow.quantity,
        paid_amount: paidAmount,
        is_paid: paidAmount >= itemTotalPrice,
        created_at: itemRow.created_at,
      };
    });

    return res.json({
      success: true,
      data: items,
    });
  } catch (error: any) {
    console.error('Error fetching items:', error);
    return res.status(500).json({
      success: false,
      error: error.message,
    });
  }
});

// POST /api/v1/tickets/:ticketId/items - Add items to a ticket
router.post('/:ticketId/items', async (req: Request, res: Response) => {
  try {
    await simulateDelay();
    
    if (shouldSimulateFailure()) {
      return res.status(500).json({
        success: false,
        error: 'Simulated server error',
      });
    }

    const { ticketId } = req.params;
    const { items } = req.body as AddItemsRequest;

    if (!items || !Array.isArray(items) || items.length === 0) {
      return res.status(400).json({
        success: false,
        error: 'items array is required',
      });
    }

    // Verify ticket exists and is open
    const ticketResult = await pool.query(
      'SELECT * FROM tickets WHERE tickets.id = $1',
      [ticketId]
    );

    if (ticketResult.rows.length === 0) {
      return res.status(404).json({
        success: false,
        error: 'Ticket not found',
      });
    }

    const ticket = ticketResult.rows[0];
    if (ticket.status === 'CANCELLED') {
      return res.status(400).json({
        success: false,
        error: 'Cannot add items to a cancelled ticket',
      });
    }

    if (ticket.status === 'PAID') {
      return res.status(400).json({
        success: false,
        error: 'Cannot add items to a fully paid ticket',
      });
    }

    const addedItems: TicketItem[] = [];

    // Insert items (UUID auto-generated by database)
    for (const item of items) {
      if (!item.name || item.price === undefined || !item.quantity) {
        return res.status(400).json({
          success: false,
          error: 'Each item must have name, price, and quantity',
        });
      }

      if (item.quantity <= 0) {
        return res.status(400).json({
          success: false,
          error: 'Quantity must be greater than 0',
        });
      }

      if (item.price < 0) {
        return res.status(400).json({
          success: false,
          error: 'Price must be non-negative',
        });
      }

      const result = await pool.query(
        `INSERT INTO ticket_items (ticket_id, name, price, quantity, paid_amount, created_at)
         VALUES ($1, $2, $3, $4, 0, NOW())
         RETURNING 
           ticket_items.id,
           ticket_items.ticket_id,
           ticket_items.name,
           ticket_items.price,
           ticket_items.quantity,
           ticket_items.paid_amount,
           ticket_items.created_at`,
        [ticketId, item.name, item.price, item.quantity]
      );

      const row = result.rows[0];
      const paidAmount = row.paid_amount || 0;
      const itemTotalPrice = row.price * row.quantity;
      
      addedItems.push({
        id: row.id,
        ticket_id: row.ticket_id,
        name: row.name,
        price: row.price,
        quantity: row.quantity,
        paid_amount: paidAmount,
        is_paid: paidAmount >= itemTotalPrice,
        created_at: row.created_at,
      });
    }

    // Recalculate ticket total_amount
    const allItemsResult = await pool.query(
      `SELECT 
        ticket_items.price,
        ticket_items.quantity
      FROM ticket_items 
      WHERE ticket_items.ticket_id = $1`,
      [ticketId]
    );

    const totalAmount = allItemsResult.rows.reduce(
      (sum, row) => sum + row.price * row.quantity,
      0
    );

    // Update ticket total_amount
    await pool.query(
      `UPDATE tickets 
       SET total_amount = $1, 
           updated_at = NOW() 
       WHERE tickets.id = $2`,
      [totalAmount, ticketId]
    );

    return res.status(201).json({
      success: true,
      data: addedItems,
    });
  } catch (error: any) {
    console.error('Error adding items:', error);
    return res.status(500).json({
      success: false,
      error: error.message,
    });
  }
});

// DELETE /api/v1/items/:itemId - Remove item from ticket and recalc total
router.delete('/:itemId', async (req: Request, res: Response) => {
  try {
    await simulateDelay();
    if (shouldSimulateFailure()) {
      return res.status(500).json({ success: false, error: 'Simulated server error' });
    }
    const { itemId } = req.params;

    const itemResult = await pool.query(
      'SELECT id, ticket_id, paid_amount, price, quantity FROM ticket_items WHERE ticket_items.id = $1',
      [itemId]
    );
    if (itemResult.rows.length === 0) {
      return res.status(404).json({ success: false, error: 'Item not found' });
    }
    const item = itemResult.rows[0];
    const ticketId = item.ticket_id;

    const ticketResult = await pool.query('SELECT * FROM tickets WHERE tickets.id = $1', [ticketId]);
    if (ticketResult.rows.length === 0) {
      return res.status(404).json({ success: false, error: 'Ticket not found' });
    }
    const ticket = ticketResult.rows[0];
    if (ticket.status === 'PAID') {
      return res.status(400).json({ success: false, error: 'Cannot remove items from a paid ticket' });
    }
    if (item.paid_amount > 0) {
      return res.status(400).json({ success: false, error: 'Cannot remove item that has paid amount' });
    }

    await pool.query('DELETE FROM ticket_items WHERE ticket_items.id = $1', [itemId]);

    const sumResult = await pool.query(
      `SELECT COALESCE(SUM(ticket_items.price * ticket_items.quantity), 0)::integer AS total
       FROM ticket_items WHERE ticket_items.ticket_id = $1`,
      [ticketId]
    );
    const totalAmount = sumResult.rows[0].total;

    await pool.query(
      'UPDATE tickets SET total_amount = $1, updated_at = NOW() WHERE tickets.id = $2',
      [totalAmount, ticketId]
    );

    return res.status(200).json({ success: true, total_amount: totalAmount });
  } catch (error: any) {
    console.error('Error deleting item:', error);
    return res.status(500).json({ success: false, error: error.message });
  }
});

// PATCH /api/v1/items/:itemId - Update item (quantity or notes)
router.patch('/:itemId', async (req: Request, res: Response) => {
  try {
    await simulateDelay();
    if (shouldSimulateFailure()) {
      return res.status(500).json({ success: false, error: 'Simulated server error' });
    }

    const { itemId } = req.params;
    const body = req.body as { quantity?: number; notes?: string };

    const itemResult = await pool.query(
      `SELECT id, ticket_id, name, price, quantity, paid_amount, created_at
       FROM ticket_items WHERE ticket_items.id = $1`,
      [itemId]
    );
    if (itemResult.rows.length === 0) {
      return res.status(404).json({ success: false, error: 'Item not found' });
    }
    const item = itemResult.rows[0];

    const ticketResult = await pool.query(
      'SELECT * FROM tickets WHERE tickets.id = $1',
      [item.ticket_id]
    );
    if (ticketResult.rows.length === 0) {
      return res.status(404).json({ success: false, error: 'Ticket not found' });
    }
    const ticket = ticketResult.rows[0];
    if (ticket.status === 'CANCELLED') {
      return res.status(400).json({ success: false, error: 'Cannot update items on a cancelled ticket' });
    }
    if (ticket.status === 'PAID') {
      return res.status(400).json({ success: false, error: 'Cannot update items on a paid ticket' });
    }

    let newQuantity = item.quantity;
    if (typeof body.quantity === 'number' && body.quantity >= 0) {
      newQuantity = Math.max(0, Math.floor(body.quantity));
      if (newQuantity === 0) {
        await pool.query('DELETE FROM ticket_items WHERE ticket_items.id = $1', [itemId]);
        const sumResult = await pool.query(
          `SELECT COALESCE(SUM(ticket_items.price * ticket_items.quantity), 0)::integer AS total
           FROM ticket_items WHERE ticket_items.ticket_id = $1`,
          [item.ticket_id]
        );
        await pool.query(
          'UPDATE tickets SET total_amount = $1, updated_at = NOW() WHERE tickets.id = $2',
          [sumResult.rows[0].total, item.ticket_id]
        );
        return res.json({ success: true, data: null, deleted: true });
      }
      await pool.query(
        'UPDATE ticket_items SET quantity = $1 WHERE ticket_items.id = $2',
        [newQuantity, itemId]
      );
    }

    const sumResult = await pool.query(
      `SELECT COALESCE(SUM(ticket_items.price * ticket_items.quantity), 0)::integer AS total
       FROM ticket_items WHERE ticket_items.ticket_id = $1`,
      [item.ticket_id]
    );
    await pool.query(
      'UPDATE tickets SET total_amount = $1, updated_at = NOW() WHERE tickets.id = $2',
      [sumResult.rows[0].total, item.ticket_id]
    );

    const updatedResult = await pool.query(
      `SELECT id, ticket_id, name, price, quantity, paid_amount, created_at
       FROM ticket_items WHERE ticket_items.id = $1`,
      [itemId]
    );
    const row = updatedResult.rows[0];
    const paidAmount = row.paid_amount || 0;
    const updatedItem: TicketItem = {
      id: row.id,
      ticket_id: row.ticket_id,
      name: row.name,
      price: row.price,
      quantity: row.quantity,
      paid_amount: paidAmount,
      is_paid: paidAmount >= row.price * row.quantity,
      created_at: row.created_at,
    };

    return res.json({ success: true, data: updatedItem });
  } catch (error: any) {
    console.error('Error updating item:', error);
    return res.status(500).json({ success: false, error: error.message });
  }
});

export default router;
